package com.rehman.ahmedreactionstudio.editor

import android.content.Context
import android.graphics.Color
import android.graphics.drawable.Drawable
import android.graphics.drawable.GradientDrawable
import android.view.HapticFeedbackConstants
import android.view.MotionEvent
import android.view.View
import android.view.animation.OvershootInterpolator
import android.widget.FrameLayout
import android.widget.ImageView
import com.rehman.ahmedreactionstudio.R
import com.rehman.ahmedreactionstudio.util.UI

/**
 * Modern vector-icon toolkit (OBS plan §4.1).
 *
 * All icons are Material-style vector drawables in res/drawable (compiled by
 * aapt2; the R class is generated by build-apk.sh step 2/7). [icon] returns a
 * tinted copy, [IconBtn] is the animated button used across the studio UI.
 */
object Ic {

    /** type icon for a source kind */
    fun typeIcon(t: com.rehman.ahmedreactionstudio.core.LayerType): Int = when (t) {
        com.rehman.ahmedreactionstudio.core.LayerType.VIDEO -> R.drawable.ic_video
        com.rehman.ahmedreactionstudio.core.LayerType.CAMERA -> R.drawable.ic_camera
        com.rehman.ahmedreactionstudio.core.LayerType.SCREEN -> R.drawable.ic_screen
        com.rehman.ahmedreactionstudio.core.LayerType.IMAGE -> R.drawable.ic_image
        com.rehman.ahmedreactionstudio.core.LayerType.TEXT -> R.drawable.ic_text
    }

    fun get(ctx: Context, resId: Int, tint: Int = UI.FG): Drawable {
        val d = ctx.resources.getDrawable(resId, ctx.theme).mutate()
        d.setTint(tint)
        return d
    }

    /** pill/circle background used by the floating controls */
    fun pill(ctx: Context, color: Int, radiusDp: Float = 20f,
             stroke: Int = Color.argb(60, 255, 255, 255)): GradientDrawable {
        val g = GradientDrawable()
        g.cornerRadius = UI.dpf(ctx, radiusDp)
        g.setColor(color)
        g.setStroke(1, stroke)
        return g
    }
}

/**
 * An icon button with premium micro-interactions:
 *  - press pulse (dips to 86 % and springs back with overshoot)
 *  - haptic tick on press
 *  - engaged/disengaged tint states
 */
class IconBtn(context: Context) : FrameLayout(context) {

    val image = ImageView(context)
    private var downScale = false

    init {
        val pad = UI.dp(context, 8)
        image.setPadding(pad, pad, pad, pad)
        addView(image, LayoutParams(LayoutParams.MATCH_PARENT, LayoutParams.MATCH_PARENT))
        isClickable = true
        isFocusable = true
    }

    fun setIcon(resId: Int, tint: Int = UI.FG, desc: String? = null) {
        image.setImageDrawable(Ic.get(context, resId, tint))
        // TalkBack label for an otherwise silent icon button. Call sites pass a
        // short verb ("Mute", "Hide"); when null the previous label is kept.
        if (desc != null) contentDescription = desc
    }

    /** animated icon swap: quick dip + swap + spring back */
    fun setIconAnimated(resId: Int, tint: Int = UI.FG) {
        animate().cancel()
        animate().scaleX(0.72f).scaleY(0.72f).setDuration(70).withEndAction {
            setIcon(resId, tint)
            animate().scaleX(1f).scaleY(1f).setDuration(240)
                .setInterpolator(OvershootInterpolator(2.2f)).start()
        }.start()
    }

    override fun onTouchEvent(event: MotionEvent): Boolean {
        when (event.actionMasked) {
            MotionEvent.ACTION_DOWN -> {
                downScale = true
                performHapticFeedback(HapticFeedbackConstants.VIRTUAL_KEY)
                animate().cancel()
                animate().scaleX(0.86f).scaleY(0.86f).setDuration(80).start()
            }
            MotionEvent.ACTION_UP -> {
                if (downScale) {
                    animate().cancel()
                    animate().scaleX(1f).scaleY(1f).setDuration(300)
                        .setInterpolator(OvershootInterpolator(2.6f)).start()
                }
            }
            MotionEvent.ACTION_CANCEL -> {
                animate().cancel()
                animate().scaleX(1f).scaleY(1f).setDuration(150).start()
            }
        }
        return super.onTouchEvent(event)
    }

    companion object {
        /** standard size for quick-control buttons */
        fun sized(ctx: Context, dpSize: Int = 42): LayoutParams =
            LayoutParams(UI.dp(ctx, dpSize), UI.dp(ctx, dpSize))
    }
}
